name:                wsUI
version:             0.1.0.0
github:              "jhoxray/wsUI"
license:             BSD3
author:              "J X-Ray Ho"
maintainer:          "jho.xray@gmail.com"
copyright:           "Copyright: (c) 2016 J X-Ray Ho"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            languages

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/jhoxray/wsUI#readme>

dependencies:
- base >= 4.7 && < 5
- websockets
- text
- directory
- open-browser
- aeson
- hml-accelerate # local package referenced by stack.yaml
- containers
- gl
- GLFW-b
- bindings-GLFW
- monad-loops
- nanovg
- transformers
- vector

library:
  source-dirs: src

executables:
  wsUI-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wsUI

  simple-todo:
    main:                Main.hs
    source-dirs:         examples/minimal
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wsUI

  nanovg:
    main:                Main.hs
    source-dirs:         examples/nanovg-default
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wsUI

tests:
  wsUI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wsUI
